pokemap/pokemap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokesearch.urls')),
]

pokemap/pokesearch/urls.py
from django.urls import path

from .views import HomePageView, SearchResultsView

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('', HomePageView.as_view(), name='home'),
]

pokemap/pokesearch/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class PokemonSpecies(models.Model):
    id = models.IntegerField(
        primary_key=True, help_text="The identifier for this resource."
    )
    name = models.CharField(
        _("name"), max_length=32, help_text="The name for this resource."
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Pokemon species"
        verbose_name_plural = "Pokemon species"
        ordering = ['id']


class Type(models.Model):
    id = models.IntegerField(
        primary_key=True, help_text="The identifier for this resource."
    )
    name = models.CharField(
        _("name"), max_length=32, help_text="The name for this resource."
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Type"
        verbose_name_plural = "Types"
        ordering = ['id']


class Pokemon(models.Model):
    id = models.IntegerField(
        primary_key=True, help_text="The identifier for this resource."
    )
    name = models.CharField(
        _("name"), max_length=32, help_text="The name for this resource."
    )
    species = models.ForeignKey(
        PokemonSpecies,
        on_delete=models.CASCADE,
        help_text="The species this Pokémon belongs to.",
        blank=True,
        null=True,
    )
    types = models.ManyToManyField(
        Type,
        through="PokemonType",
        help_text="A list of details showing types this Pokémon has.",
        blank=True
    )
    created = models.DateTimeField(
        _("Creation Date and Time"),
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        _("Modification Date and Time"),
        auto_now=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Pokemon"
        verbose_name_plural = "Pokemons"
        ordering = ['id']


class PokemonType(models.Model):
    slot = models.IntegerField(
        _("slot"), help_text="The order the Pokémon's types are listed in."
    )
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.pokemon.name}: {self.slot}: {self.type.name}"

    class Meta:
        verbose_name = "Pokemon type"
        verbose_name_plural = "Pokemon types"
        ordering = ['pokemon', 'slot']

pokemap/pokesearch/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.db.models import Q

import requests
import requests_cache

from .models import Pokemon


requests_cache.install_cache('pokesearch_cache')

class HomePageView(TemplateView):
    template_name = 'home.html'

class SearchResultsView(ListView):
    model = Pokemon
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Pokemon.objects.filter(
            Q(name__icontains=query)
        )

        for obj in object_list:
            pokemon = requests.get(f"https://pokeapi.co/api/v2/pokemon/{obj.id}")
            obj.sprite_front = pokemon.json()["sprites"]["front_default"]
            obj.height = pokemon.json()["height"]
            obj.weight = pokemon.json()["weight"]
            obj.sprite_back = pokemon.json()["sprites"]["back_default"]
        return object_list

pokemap/templates/base.html
{% load static %}
<html>

<head>
    <title>Mapologo's Pokemon Search</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <style>
        .v-card--reveal {
            bottom: 0;
            opacity: 1 !important;
            position: absolute;
            width: 100%;
        }
    </style>
</head>

<body>
    <div id="app">
        <v-app>
            <v-main>
                <v-app-bar app class="white">
                    <img alt="Pokémon logo English.png"
                        src="//cdn.bulbagarden.net/upload/thumb/d/d2/Pok%C3%A9mon_logo_English.png/200px-Pok%C3%A9mon_logo_English.png"
                        width="150" height="56">
                    <v-divider class="mx-8" vertical></v-divider>
                    <div class="text-h4 red--text font-weight-black">
                        Search
                    </div>

                </v-app-bar>

                <v-main>
                    <v-container>
                        {% block content %}{% endblock %}
                    </v-container>
                </v-main>

                <v-footer app class="white">
                    <v-card flat tile width="100%" class="white lighten-1 text-center">
                        <v-card-text class="red--text">
                            [[ new Date().getFullYear() ]] — <strong>Mapologo</strong>
                        </v-card-text>
                    </v-card>
                </v-footer>
            </v-main>
        </v-app>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
    <script>
        new Vue({
            el: '#app',
            vuetify: new Vuetify({
                theme: { dark: true },
            }),
            delimiters: ['[[', ']]'],
            data: () => ({
                valid: false,
                reveal: false,
                pokemonname: '',
                message: 'Hola Vue!',
                nameRules: [
                    v => !!v || 'Name is required',
                    v => v.length <= 21 || 'Name must be less than 21 characters',
                ]
            }),
        })
    </script>


</body>

</html>

pokemap/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="text-h4">
    <a href="/">
        <v-icon large color="red darken-2">
            mdi-home
        </v-icon>
    </a>
</div>
<v-form v-model="valid" action="{% url 'search_results' %}" method="get">
    <v-container>
        <v-row>
            <v-col cols="12" md="4">
                <v-text-field v-model="pokemonname" :rules="nameRules" :counter="21" label="Pokemon name" required
                    name="q" placeholder="Search..."></v-text-field>
            </v-col>
        </v-row>
    </v-container>
</v-form>
{% endblock %}

pokemap/templates/search_results.html
{% extends "base.html" %}
{% block content %}<div class="text-h4">
    <a href="/">
        <v-icon large color="red darken-2">
            mdi-home
        </v-icon>
    </a>
</div>
<v-form v-model="valid" action="{% url 'search_results' %}" method="get">
    <v-container>
        <v-row>
            <v-col cols="12" md="4">
                <v-text-field v-model="pokemonname" :rules="nameRules" :counter="21" label="Pokemon name" required
                    name="q" placeholder="Search..."></v-text-field>
            </v-col>
        </v-row>
    </v-container>
</v-form>
<h1>Search Results</h1>

<div>
    <v-card max-width="600" class="mx-auto">
        <v-container>
            <v-row dense>
                <v-col cols="12">
                    {% for pokemon in pokemon_list %}
                    <v-card class="ma-8">
                        <div class="d-flex flex-no-wrap justify-space-between" elevation="10">
                            <div>
                                <v-card-subtitle>{{ pokemon.id }}</v-card-subtitle>
                                <v-card-title class="headline">{{ pokemon.name }}</v-card-title>
                                <v-card-actions>
                                    <v-btn text color="teal accent-4" @click="reveal = true">
                                        Learn More
                                    </v-btn>
                                </v-card-actions>
                            </div>
                            <v-avatar class="ma-3" size="125" tile>
                                <v-img src="{{ pokemon.sprite_front }}"></v-img>
                            </v-avatar>

                            <v-expand-transition>
                                <v-card v-if="reveal" class="transition-fast-in-fast-out v-card--reveal"
                                    style="height: 100%;">
                                    <div class="d-flex flex-no-wrap justify-space-between" elevation="10">
                                        <div>
                                            <v-card-title> Info </v-card-title>
                                            <v-card-text>
                                                <div class="text--primary">
                                                    height: {{ pokemon.height }} dm <br>
                                                    weight: {{ pokemon.weight }} hg
                                                </div>
                                            </v-card-text>

                                            <v-card-actions class="pt-0">
                                                <v-btn text color="teal accent-4" @click="reveal = false">
                                                    Close
                                                </v-btn>
                                            </v-card-actions>
                                        </div>
                                        <v-avatar class="ma-3" size="125" tile>
                                            <v-img src="{{ pokemon.sprite_back }}"></v-img>
                                        </v-avatar>
                                    </div>
                                </v-card>
                            </v-expand-transition>

                        </div>
                    </v-card>
                    {% endfor %}
                </v-col>
            </v-row>
        </v-container>
    </v-card>
    </ul>
</div>

{% endblock %}